/**
 * This code was generated by Builder.io.
 */
import React from "react";
import HeroSection from "../../components/top-title/HeroSection";
// import StorySection from "./Components/StorySection";
// import OurStorySection from "./Components/OurStorySection";
// import ChefSection from "./Components/ChefSection";
// import SpecialServices from "./Components/SpecialService/SpecialServices";
import TeamSection from "./Components/TeamSection/TeamSection";
import layoutService from "../../utils/layout/layout.service";
import { useQuery } from "@tanstack/react-query";
import JSXParser from "react-jsx-parser";
// import { useNavigate } from "react-router-dom";

const AboutUs: React.FC = () => {
    // const navigate = useNavigate();
    const fetchLayout = async () => {
        const response = await layoutService.apiGetLayout("about");

        return response.data.result;
    };
    const { data } = useQuery({
        queryKey: ["layout", "about"],
        queryFn: () => fetchLayout(),
    });
    return (
        <main className="flex flex-col items-center">
            <HeroSection
                title="About us"
                description="Lorem Ipsum is simply dummy text of the printing and typesetting industry"
            />
            <div className="w-screen h-auto flex flex-col justify-center items-center bg-main overflow-x-hidden gap-[50px] lg:px-0 px-[30px]">
                {/* <StorySection />
                <OurStorySection />
                <ChefSection /> */}
                {/* <SpecialServices services={services} /> */}
           
                <div className="flex flex-col items-center justify-center w-full max-sm:px-2 sm:px-[100px] gap-[30px]">
                    {data &&
                        data.map((item: any, index: number) => (
                            <JSXParser
                                key={index}
                                jsx={item.code}
                                bindings={{}}
                                components={{}}
                                renderInWrapper={false}
                            />
                        ))}
                </div>
                <TeamSection />
            </div>
        </main>
    );
};

export default AboutUs;
